# numerai-models workflow on paperspace gradient

on:
  github:
    branches:
      only: main

defaults:
  env:
    PUBLIC_ID: secret:PUBLIC_ID
    SECRET_KEY: secret:SECRET_KEY
  resources:
    instance-type: P4000

jobs:

  # 1: clone repo to instance
  cloneRepo:
    outputs:
      repo:
        type: volume
    uses: git-checkout@v1
    with:
      url: https://github.com/hiydavid/numerai-models.git

  # 2: get data and make predictions
  runLivePredictions:
    needs:
      - cloneRepo
    inputs:
      repo: cloneRepo.outputs.repo
    outputs:
      data:
        type: volume
      predictions:
        type: volume
    uses: script@v1
    with:
      script: |-
        pip3 install numerapi==2.11.0
        pip3 install pyarrow
        pip3 install fastparquet
        pip3 install lightgbm==3.3.0
        pip3 install tensorflow_recommenders
        cp -R /inputs/repo /numerai-models
        cd /numerai-models
        mkdir -p predictions
        python3 run.py
      image: tensorflow/tensorflow:2.9.2
